name: Deploy CodeSectorCMS.MessageService to Azure AppService

on:
  push:
    paths:
      - 'CodeSectorCMS.MessageService/**'
      - 'CodeSectorCMS.Domain/**'
      - '.github/workflows/deploy-to-Azure-MessageService-project.yaml'
  pull_request:
    paths:
        - 'CodeSectorCMS.MessageService/**'
        - 'CodeSectorCMS.Domain/**'
        - '.github/workflows/deploy-to-Azure-MessageService-project.yaml'
  workflow_dispatch:

env:
  WEB_SERVER_NAME: "CodeSectorCMS-Web"
  WEB_SERVER_NAME_ENV: "CodeSectorCMS.Web"
  SERVER_APP_NAME: "CodeSectorCMS-MessageService"
  RESOURCE_GROUP: "CodeSector"

permissions:
  id-token: write
  contents: read

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Install dependencies
        run: dotnet restore ./CodeSectorCMS.MessageService/CodeSectorCMS.MessageService.csproj

      - name: Build
        run: dotnet build ./CodeSectorCMS.MessageService/CodeSectorCMS.MessageService.csproj

      - name: Publish
        run: dotnet publish ./CodeSectorCMS.MessageService/CodeSectorCMS.MessageService.csproj --configuration Release --output ./publish

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Update App Service Connection String
        run: |
          az webapp config connection-string set --name ${{ env.SERVER_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --settings CMSContext="${{ secrets.DB_SOMEE_CONNECTION_STRING }}" --connection-string-type SqlServer

      - name: Update App Service Bus Connection String
        run: |
          az webapp config connection-string set --name ${{ env.SERVER_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --settings AzureServiceBus="${{ secrets.AZURE_SERVICE_BUS }}" --connection-string-type ServiceBus

      - name: Update App Service CodeSectorCMS.Web endpoint
        run: |
          DEFAULT_DOMAIN=$(az webapp show --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.WEB_SERVER_NAME }} --query "defaultHostName" --output tsv)
          az webapp config appsettings set --name ${{ env.SERVER_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --settings ${{ env.WEB_SERVER_NAME_ENV }}="$DEFAULT_DOMAIN"

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.SERVER_APP_NAME }}
          publish-profile: ${{ secrets.SERVER_PUBLISH_PROFILE_MESSAGESERVICE }}
          package: ./publish