name: Deploy CodeSectorCMS.Web to Azure AppService

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  SERVER_APP_NAME: "CodeSectorCMS-Web"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Install dependencies
        run: dotnet restore ./CodeSectorCMS.Web/CodeSectorCMS.Web.csproj

      - name: Build
        run: dotnet build ./CodeSectorCMS.Web/CodeSectorCMS.Web.csproj

      - name: Publish
        run: dotnet publish ./CodeSectorCMS.Web/CodeSectorCMS.Web.csproj --configuration Release --output ./publish

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.SERVER_APP_NAME }}
          publish-profile: ${{ secrets.SERVER_PUBLISH_PROFILE }}
          package: ./publish